backend:
  name: git-gateway
  branch: main
media_folder: 'assets/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: donation-goals
    label: Objectifs de dons
    label_singular: Objectif de don
    folder: content/donation-goals
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Brouillon, name: draft, default: false, widget: "boolean" }
      - { label: Titre, name: title }
      - { label: Montant, name: amount, widget: "number", value_type: "int" }
      - { label: "Objectif atteint", name: done, default: false, widget: "boolean" }