backend:
  name: git-gateway
  branch: main
media_folder: 'assets/media'
public_folder: '/media'
locale: fr
slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: achievements
    label: Objectifs
    label_singular: Objectif
    folder: content/achievements
    create: true
    editor: { preview: false }
    filter: {field: "visibleInCms", value: true}
    fields:
      - { label: "Visible", name: "visibleInCms", widget: hidden, default: true}
      - { label: Brouillon, name: draft, default: false, widget: "boolean" }
      - { label: Titre, name: title }
      - { label: "Objectif atteint", name: done, default: false, widget: "boolean" }